routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Gloudemans\Shoppingcart\Facades\Cart;

// Route::get('/', function () {
//     return view('/home');
// });

// Auth::routes();

// // Route::get('/home', 'HomeController@index')->name('home');
// Route::get('/', 'HomeController@index')->name('home');

// Route::group ([ 'middleware' => [ 'auth' ]], function () {
//     // Route::resource ('roles', 'RoleController');
//     Route::resource('user', 'UserController');
// });
// // Route::get('/user/{user}/edit ', 'UserController@edit')->name('user.edit');//modif compte utilisateur
// // Route::put('/user/{user}', 'UserController@update')->name('user.update');

// Route::group(['middleware' => ['role:admin']], function() {
//     Route::get('/admin', function() {
//         return view('admin.homeadmin');
//     });
// });
// Route::group(['middleware' => ['role:customer']], function() {
//     Route::get('/customer', function() {
//         return view('home');
//     });
// });
// //Route errors
// Route::fallback(function()
// {
//     return view('error404');
// });
// /*------------------------------- Routes Panier---------------------*/
// /**
//  * products routes
//  */
// //Route::resource ('product', 'ProductController');
// Route::get('/product/{product}', 'ProductController@show')->name('product.show');
// Route::get('/burgersPage', 'ProductController@index');
// /**
//  * drinks routes
//  */
// Route::get('/drinksPage', 'DrinkController@index');
// /**
//  * cart routes
//  */
// Route::get('/cart', 'CartController@index')->name('cart.index');
// Route::post('/cart', 'CartController@store')->name('cart.store');
// Route::patch('/cart/{rowId}', 'CartController@update')->name('cart.update');
// Route::delete('/cart/{rowId}', 'CartController@destroy')->name('cart.destroy');

// //Route::delete('/cart/{product}', 'CartController@destroy')->name('destroyCart');

// Route::get('/emptycart', function() {
//     Cart::destroy();
// });


/////////////////////////////
Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

//////test
Route::group(['middleware' => ['role:admin']], function() {
    Route::get('/admin', function() {
        return view('admin.homeadmin');
    });
});

// PRODUCTS vues sans connexion!----------------------à voir avec Olivier!

Route::get('menusPage', 'DrinkController@edit');//vue menu
Route::get('burgersPage', 'ProductController@index');//vue burger
Route::get('drinksPage', 'DrinkController@index');//vue boisson
Route::get('saucesPage', 'DrinkController@show');//vue sauces
Route::get('accPage', 'ProductController@show');//vue accompagnement
/////////////////////////////////////////////////////////////////////
//pour pouvoir executer sans être connecté:
Route::resource('cart', 'CartController');
Route::resource('user', 'UserController');
// ADMIN & CUSTOMER vues que si on est connecté!
Route::group(['middleware' => ['role:admin|customer']], function() {
    
    // Route::resource('product', 'ProductController')->only('index');
    Route::resource('product', 'ProductController');

});

// ADMIN
Route::group(['middleware' => ['role:admin']], function() {
    // Route::resource('product', 'ProductController')->except('index');
    Route::resource('product', 'ProductController');

   

});

Route::fallback(function()
{
    return view('home');
});
/////////////////////////////

resources/views/viewUser/listUsers.blade.php
    @extends('layouts.appadmin')
    @section('title')
Back office
@endsection

    @section('content')
    <div class="container">
    <div class="section-container">
            <div>
              @if (session('success'))
              <div class="alert alter-success" role="alert">
                {{ session('success') }}
        </div>
              @endif
<table>
    <tr>
        <th>Id</th>
        <th>Email</th>
    </tr>
    @foreach($user as $user)
    <tr>
        <td>{{ $user->id }}</td>
        <td>{{ $user->email }}</td>
        <td><form method="GET" action="{{ route('user.edit', $user->id) }}">
    @csrf
    @method('EDIT')
    <input class="btn btn-danger" type="submit" value="Modifier">
</form></td>
        <td><form method="POST" action="{{ route('user.destroy', $user->id) }}"
        onsubmit="return confirm('Etes vous sur de vouloir définitivement supprimer l\'entrée?');">
    @csrf
    @method('DELETE')
    <input class="btn btn-danger" type="submit" value="Supprimer">
</form></td>

</tr>
    @endforeach
</table>
</div>
@endsection

resources/views/viewUser/updateCompte.blade.php
@extends('layouts.appadmin')
@section('content')
<div class="container">
    <div class="section-container">
            <div>
              @if (session('success'))
              <div class="alert alter-success" role="alert">
                {{ session('success') }}
        </div>
              @endif
    <div class="card-body">
    <table>
    <tr>
        <th>Prenom</th>
        <th>Nom</th>
        <th>Numéro de telephone</th>
        <th>Adresse</th>
        <th>Mail</th>
        <th>Mot de passe</th>
    </tr>
    @csrf
    <tr>
        <td>{{ Auth::user()->firstName }}</td>
        <td>{{ Auth::user()->name }}</td>
        <td>{{ Auth::user()->phoneNumber }}</td>
        <td>{{ Auth::user()->address }}</td>
        <td>{{ Auth::user()->email }}</td>
        <td>{{ Auth::user()->password_hash }}</td>
    </tr>

    <form action="{{ route('user.update', Auth::user()->id) }}" method="POST">
                    {{ csrf_field() }}
                    {{ method_field('PUT')}}
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>
                        <input type="text" name="firstName" class="form-control" placeholder="{{ Auth::user()->firstName }}">
                    </div>
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>
                        <input type="text" name="name" class="form-control" placeholder="{{ Auth::user()->name }}">
                    </div>
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>
                        <input type="text" name="phoneNumber" class="form-control" placeholder="{{ Auth::user()->phoneNumber }}">
                    </div>
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>
                        <input type="text" name="address" class="form-control" placeholder="{{ Auth::user()->address }}">
                    </div>
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>
                        <input type="text" name="email" class="form-control" placeholder="{{ Auth::user()->email }}">
                    </div>
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>
                        <input type="password" name="password" class="form-control" placeholder="mot de passe">
                    </div>
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>
                        <input type="password" name="confirmpassword" class="form-control" placeholder="Confirmer mot de passe">
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Modifier" class="btn btn-danger">
                        <input type="reset" value="Annuler" onclick="location.href='/'" class="btn float-right cancel_btn">

                    </div>    

</div>  
    
</table>
                
@endsection

resources/views/viewUser/updateUser.blade.php
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
 
    @include('header')
</head>
<body>
@section('content')
<div class="container">
<div class="section-container">
            <div>
              @if (session('success'))
              <div class="alert alter-success" role="alert">
                {{ session('success') }}
        </div>
              @endif
    <div class="card-body">
    <table>
    <tr>
        <th>Id</th>
        <th>Prenom</th>
        <th>Nom</th>
        <th>Numéro de telephone</th>
        <th>Adresse</th>
        <th>Mail</th>
        <th>Mot de passe</th>
    </tr>
    @csrf
    
    <tr>
        <td>{{ $user->id }}</td>
        <td>{{ $user->firstName }}</td>
        <td>{{ $user->name }}</td>
        <td>{{ $user->phoneNumber }}</td>
        <td>{{ $user->address }}</td>
        <td>{{ $user->email }}</td>
        <td>{{ $user->password_hash }}</td>
    </tr>  
</table>
                <form action="{{ route('user.update', $user->id) }}" method="PUT">
                    {{ csrf_field() }}
                    {{ method_field('PUT')}}
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-user">{{ __('Prenom') }}</i></span>
                        </div>
                        <input type="text" name="firstName" class="form-control" placeholder="{{ $user->firstName }}">
                    </div>
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-user">{{ __('Nom') }}</i></span>
                        </div>
                        <input type="text" name="name" class="form-control" placeholder="{{ $user->name }}">
                    </div>
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-user">{{ __('Telephone') }}</i></span>
                        </div>
                        <input type="text" name="phoneNumber" class="form-control" placeholder="{{ $user->phoneNumber }}">
                    </div>
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-user">{{ __('Adresse') }}</i></span>
                        </div>
                        <input type="text" name="address" class="form-control" placeholder="{{ $user->address }}">
                    </div>
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-user">{{ __('Email') }}</i></span>
                        </div>
                        <input type="text" name="email" class="form-control" placeholder="{{ $user->email }}">
                    </div>
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-user"></i>{{ __('Mot de passe') }}</span>
                        </div>
                        <input type="password" name="password" class="form-control @error('password') is-invalid @enderror" placeholder="mot de passe">
                    </div>
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-user">{{ __('Confirmer mot de passe') }}</i></span>
                        </div>
                        <input type="password" name="confirmpassword" class="form-control" placeholder="Confirmer mot de passe">
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Modifier" class="btn float-right login_btn">
                        <input type="reset" value="Annuler" onclick="location.href='/'" class="btn float-right cancel_btn">
                    </div>    

</div>

</body>
</html>
@include('layouts.footer')

resources/views/viewUser/userDeleted.blade.php
<p>utilisateur suprimé avec succès</p>
<a class="active" href="/">Home</a>
<a href="/user"><span class="glyphicon glyphicon-list-alt"></span> retour à la liste utilisateurs</a>